Add Codecov to CI workflow
cordada/lib-pe-sunat-python pull request #98
Opened 2023-05-23 17:18 UTC by svillegas-cdd

> Codecov is the all-in-one code coverage reporting solution for any
> test suite — giving developers actionable insights to deploy reliable
> code with confidence.

- Codecov web site: https://about.codecov.io/
- Documentation: https://docs.codecov.com/

Ref: https://cordada.aha.io/requirements/TECHINFRA-194-6
Ref: https://cordada.aha.io/features/TECHINFRA-194

2023-05-25 19:54 UTC, fpinto-cdd approved these changes

2023-05-25 23:23 UTC, jtrobles-cdd requested changes

2023-05-25 23:23 UTC, jtrobles-cdd commented on README.md
> +| [![Codecov](https://codecov.io/gh/cordada/lib-pe-sunat-python/branch/develop/graph/badge.svg)](https://codecov.io/gh/cordada/lib-pe-sunat-python) |
```suggestion
| [![Codecov](https://codecov.io/gh/cordada/lib-pe-sunat-python/branch/develop/graph/badge.svg?token=T4NJV2PI6X)](https://codecov.io/gh/cordada/lib-pe-sunat-python) |
```

2023-05-25 23:23 UTC, jtrobles-cdd commented on .coveragerc.test.ini
> +output = test_reports/coverage/xml/coverage.xml
Can you move this between `[report]` and `[xml]`?

2023-05-26 13:36 UTC, jtrobles-cdd approved these changes

2023-05-26 17:20 UTC, merged